apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: immudb
spec:
  selector:
    matchLabels:
      app: immudb
  serviceName: immudb
  replicas: 2
  template:
    metadata:
      labels:
        app: immudb
    spec:    
      initContainers:
      - name: init-immudb
        image: codenotary/immudb:latest-bullseye-slim
        command:
        - bash
        - "-c"
        - |
          set -ex
          # Generate immudb server-id from pod ordinal index.
          [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
          ordinal=${BASH_REMATCH[1]}
          #echo [immudbserv] > /mnt/conf.d/server-id.cnf
          # Add an offset to avoid reserved server-id=0 value.
          #echo server-id=$((100 + $ordinal)) >> /mnt/conf.d/server-id.cnf
          # Copy appropriate conf.d files from config-map to emptyDir.
          if [[ $ordinal -eq 0 ]]; then
            cp /mnt/config-map/primary.cnf /mnt/configs/immudb.toml
            cat /mnt/configs/immudb.toml
          else
            cp /mnt/config-map/replica.cnf /mnt/configs/immudb.toml
          fi          
        volumeMounts:
        - name: conf
          mountPath: /mnt/configs
          subPath: immudb.toml
        #- name: conf
        #  mountPath: /mnt/configs
        #  subPath: immudb.toml
        - name: config-map
          mountPath: /mnt/config-map
      containers:
      - name: immudb
        image: codenotary/immudb:latest-bullseye-slim
        #command: ["immudb"]
        command: ["immudb","--config","/mnt/configs/immudb.toml"]
        #args: ["--config='/mnt/configs/immudb.toml'"]
        env:
        - name: IMMU_ADMIN_PASSWORD
          value: "secret"
        ports:
        - name: immudbgprc
          containerPort: 3322
        - name: immudbweb
          containerPort: 8080
        volumeMounts:
        - name: data
          mountPath: /data/master
        - name: data
          mountPath: /data/replica
        #- name: immudb-config-vol
        ##  mountPath: /mnt/configs
          subPath: immudb.toml
        - name: conf
          mountPath: /mnt/configs
          subPath: immudb.toml
      volumes:
      - name: conf
        emptyDir: {} 
      - name: config-map
        configMap:
          name: immudb
      #- name: immudb-config-vol
      #   persistentVolumeClaim:
      #   claimName: immudb-volume-claim
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
