# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: immudb
  labels:
    app: immudb
spec:
  ports:
  - name: immudb
    port: 3322
  clusterIP: None
  selector:
    app: immudb
---
# Client service for connecting to any immudb instance for reads.
# For writes, you must instead connect to the primary: immudb-0.immudb.
apiVersion: v1
kind: Service
metadata:
  name: immudb-read
  labels:
    app: immudb
spec:
  ports:
  - name: immudb
    port: 3322
  selector:
    app: immudb